name: Deploy Docker Image to Server

# Required to access the workflow run details
permissions:
  contents: read
  actions: read

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the build workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest
            docker stop mleng_sayhi || true
            docker rm mleng_sayhi || true
            docker run -d --name mleng_sayhi -v /opt/assignment_outputs:/app/data ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest
