name: Build and Push Docker Image
# "best practice", according to https://docs.docker.com/guides/gha/
on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/mleng_sayhi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.DOCKER_USERNAME }}/mleng_sayhi:${{ env.TIMESTAMP }}
            ${{ vars.DOCKER_USERNAME }}/mleng_sayhi:latest
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
